-- supabase/migrations/20250930100000_create_news_table.sql

-- If the table already exists from a failed migration, drop it first.
DROP TABLE IF EXISTS public.news CASCADE;

-- ニュース記事を管理するためのテーブルを作成します。
-- Notionからの同期を想定しています。
CREATE TABLE public.news (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,

    -- NotionのページID
    notion_page_id text UNIQUE NOT NULL,

    -- 記事のメタデータ
    title text NOT NULL,
    slug text UNIQUE,
    summary text,
    cover_image_url text,

    -- 公開情報
    status text DEFAULT 'draft'::text NOT NULL, -- 'draft', 'published', 'archived'
    published_at timestamp with time zone
);

-- コメントを追加
COMMENT ON TABLE public.news IS 'News articles, potentially synced from Notion.';
COMMENT ON COLUMN public.news.notion_page_id IS 'The corresponding page ID from Notion.';
COMMENT ON COLUMN public.news.status IS 'The publication status of the article (e.g., draft, published, archived).';
COMMENT ON COLUMN public.news.slug IS 'URL-friendly slug for the article.';

-- RLS (Row Level Security) を有効化
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

-- public (非認証ユーザー含む) の読み取りを許可するポリシー
-- 公開済み(published)かつ公開日(published_at)が過去の記事のみを対象とする
CREATE POLICY "Allow public read access to published news" 
ON public.news 
FOR SELECT 
USING (status = 'published' AND published_at <= now());

-- 認証済みユーザーの操作に関するポリシー (今回は作成しません)
-- 例: CREATE POLICY "Allow admin full access" ON public.news FOR ALL USING (is_admin_user());

-- updated_at を自動更新するためのトリガーを作成
CREATE OR REPLACE FUNCTION public.handle_updated_at() 
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_news_updated
  BEFORE UPDATE ON public.news
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_updated_at();
